apiVersion: v1
kind: Service
metadata:
  name: goingress
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip-key"
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: gometrics
  type: LoadBalancer

