apiVersion: v1
kind: Service
metadata:
  name: gometrics
  labels:
    app: gometrics
spec:
  selector:
    app: gometrics
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
#  type: NodePort
