apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gometrics-monitor
  labels:
    Team: Frontend
spec:
  selector:
    matchLabels:
      app: gometrics
  endpoints:
  - port: web
    path: /metrics
    interval: 30s
