apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: gometrics
  allowCrossNamespaceImport: true
  datasource:
    database: prometheus
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
    name: gometrics
    type: prometheus
    url: http://10.166.0.2:9090
