apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared-ip-key"
spec:
  type: LoadBalancer
  ports:
  - name: web
    targetPort: 3000
    port: 3000
    protocol: TCP
  selector:
    app: grafana
---
